apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: shipops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        image: 760402325804.dkr.ecr.us-east-1.amazonaws.com/shipops/frontend:latest

        imagePullPolicy: IfNotPresent

        envFrom:
        - configMapRef:
            name: frontend-config

        ports:
        - containerPort: 80

        command:
        - /bin/sh
        - -c
        - |
          cat > /usr/share/nginx/html/env.js <<EOG
          window._env = {
            VITE_AUTH_URL: "${VITE_AUTH_URL}",
            VITE_CORE_URL: "${VITE_CORE_URL}",
            VITE_CARGO_URL: "${VITE_CARGO_URL}",
            VITE_DOCUMENT_URL: "${VITE_DOCUMENT_URL}",
            VITE_SHIPMENT_URL: "${VITE_SHIPMENT_URL}",
            VITE_AI_URL: "${VITE_AI_URL}",
            VITE_DASHBOARD_URL: "${VITE_DASHBOARD_URL}"
          };
          EOG
          exec nginx -g 'daemon off;'
