apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shipops
resources:
  - deployment.yaml
  - service.yaml
  - configmap-frontend.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: 760402325804.dkr.ecr.us-east-1.amazonaws.com/shipops/frontend
    newTag: 864bca09811d93db26be1de484cc6331dd970cc5
