apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shipops
resources:
  - deployment.yaml
  - service.yaml
  - configmap-frontend.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: 760402325804.dkr.ecr.us-east-1.amazonaws.com/shipops/frontend
    newTag: 16d996b1b78f9c53d43df1f11fa2941be88812a1
