apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ai-service
  - auth_service
  - core_service
  - documents_service
  - frontend
  - Shipment_service
  - postgres-auth
  - postgres-core
  - postgres-document
  - postgres-shipment
  - ingress
