apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: shipops
spec:
  selector:
    app: ai-service
  ports:
    - name: http
      port: 5005
      targetPort: 5005
  type: ClusterIP
