apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: documents-postgres
  namespace: shipops

spec:
  serviceName: documents-postgres

  replicas: 1

  selector:
    matchLabels:
      app: documents-postgres

  template:

    metadata:
      labels:
        app: documents-postgres

    spec:

      containers:

      - name: postgres

        image: postgres:16

        ports:
        - containerPort: 5432

        env:

        - name: POSTGRES_DB
          value: documents_db

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          value: password


        volumeMounts:

        - name: postgres-storage
          mountPath: /var/lib/postgresql/data


  volumeClaimTemplates:

  - metadata:
      name: postgres-storage

    spec:

      accessModes:
      - ReadWriteOnce

      resources:
        requests:
          storage: 2Gi