apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: shipops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:

      containers:

      - name: auth-service

        image: shipops46/auth-service:v2

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5001

        env:
        - name: PORT
          value: "5001"

        - name: NODE_ENV
          value: "production"

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: DATABASE_URL

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: JWT_SECRET

        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: REFRESH_TOKEN_SECRET
        - name: FRONTEND_ORIGIN
          value: "https://frontend.example.com"
