apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shipops
resources:
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
  - paymob-config.yaml
images:
  - name: 760402325804.dkr.ecr.us-east-1.amazonaws.com/shipops/auth
    newTag: 117e4572dea50e5f792af80a092c306b2c1760d1
