apiVersion: v1
kind: ConfigMap
metadata:
  name: paymob-config
  namespace: shipops
data:
  PAYMOB_BASE_URL: "https://accept.paymob.com"
  PAYMOB_3DS_INTEGRATION_ID: "5184251"
  PAYMOB_MOTO_INTEGRATION_ID: "5189775"
  PAYMOB_CURRENCY: "EGP"
  PAYMOB_PREMIUM_AMOUNT_CENTS: "10000"
  PAYMOB_WEBHOOK_URL: "https://webhook.site/728142c3-c3d1-4c20-89ae-0ed5b654effa"
  PAYMOB_REDIRECTION_URL: "http://k8s-shipops-frontend-a1a923278d-1330084971.us-east-1.elb.amazonaws.com/payment/success"
