apiVersion: v1
kind: Secret
metadata:
  name: auth-payment-secret
  namespace: shipops
type: Opaque
stringData:
  PAYMOB_API_KEY: ""
  PAYMOB_SECRET_KEY: ""
  PAYMOB_PUBLIC_KEY: ""
  PAYMOB_3DS_INTEGRATION_ID: ""
  PAYMOB_MOTO_INTEGRATION_ID: ""
  PAYMOB_WEBHOOK_URL: "https://your-public-auth-host/api/paymob/webhook?token=replace-me"
  PAYMOB_WEBHOOK_TOKEN: "replace-me"
  PAYMOB_YEARLY_PLAN_ID: ""
