apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: shipops
type: Opaque
stringData:
  # Database URL used by the auth service (references in-cluster auth-postgres)
  DATABASE_URL: "postgresql://postgres:password@auth-postgres:5432/shipops_db"
  JWT_SECRET: "esj7fGUem3m3JJ7mhCMqsmUxkdXbnF7cPkhr"
  REFRESH_TOKEN_SECRET: "b0d7b6b8e6c8c9f74e7e5f7b4c91d9fa8d4a67b5c3d8f1e4a9c2b7d5e8f3a1c6"
