apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - tracking-worker.yaml
images:
  - name: 760402325804.dkr.ecr.us-east-1.amazonaws.com/shipops/core
    newTag: 695da3fc55ef1da0890415e26401fd5105945494
