apiVersion: apps/v1
kind: Deployment

metadata:
  name: documents-service
  namespace: shipops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: documents-service

  template:
    metadata:
      labels:
        app: documents-service

    spec:

      containers:
      - name: documents-service

        image: rehab16/docs-service:v1   

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000

        env:
        - name: PORT
          value: "5000"

        - name: DATABASE_URL
          value: "postgresql://postgres:password@documents-postgres:5432/documents_db"

        - name: SHIPMENT_SERVICE_URL
          value: http://shipment-service:5000
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: JWT_SECRET
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: REFRESH_TOKEN_SECRET