apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-uploads
  namespace: shipops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
