apiVersion: apps/v1
kind: Deployment

metadata:
  name: shipment-service
  namespace: shipops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shipment-service


  template:

    metadata:
      labels:
        app: shipment-service


    spec:

      containers:

      - name: shipment-service

        image: rehab16/shipment-service:v3

        imagePullPolicy: IfNotPresent


        ports:

        - containerPort: 5000


        env:

        - name: PORT
          value: "5000"


        - name: DATABASE_URL
          value: "postgresql://postgres:password@shipment-postgres:5432/shipment_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: JWT_SECRET
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: REFRESH_TOKEN_SECRET
        - name: CORE_SERVICE_URL
          value: "http://core-service:5002/api/v1"