apiVersion: v1
kind: Service

metadata:
  name: shipment-service
  namespace: shipops


spec:

  selector:

    app: shipment-service


  ports:

  - port: 5000

    targetPort: 5000
  
  type: ClusterIP