apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: documents-service-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "documents-service"
      useAnnotations: true
