apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: auth-service-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "auth-service"
      useAnnotations: true